services:
  web-app:
    build:
      context: .
    environment:
      - SERVER_PORT=4000
      - DB_HOST=db
      - DB_USER=administrator
      - DB_PASS=styleworks
      - DB_CONNECTION=db:27017/mean-store
      - JWT_CERT=SECRET
    links:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my_data:/data/db

volumes:
  my_data:
          
